env:
  browser: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  sourceType: module
rules:
  indent:
    - 0
    - tab
  linebreak-style:
    - 0
    - unix
  quotes:
    - 0
    - double
  semi:
    - 0
    - always
